import Image from 'next/image'
import React from 'react'
import Details from './details/details'
import Total from './total/total'
import View from './view/view'
import ProductSection from './product/product-section'
import Sidbar from './sidbar/sidbar'
import Head from 'next/head'

export default function Single() {
  return (
    <>
      <Head>
          <title>فروشگاه - مشاهده محصول</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="page-content mt-5">
          <div className="container">

              <div className="row gutter-lg">
                  <div className="main-content">
                      <View/>
                      {/* <Total/> */}
                      {/* <Details/> */}
                      {/* <ProductSection/> */}
                  </div>
                  {/* <Sidbar/> */}
              </div>

          </div>
      </div>
    </>
  )
}

