import React from 'react'
import Link from 'next/link'
import Head from 'next/head'
import Single from 'components/single/single'

export default function Product() {
  return (
    <>
        <Head>
            <title>فروشگاه - مشاهده محصول</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <nav className="breadcrumb-nav rtl">
            <div className="container">
                <ul className="breadcrumb">
                    <li><Link href="/">خانه</Link></li>
                    <li>مشاهده محصول</li>
                </ul>
            </div>
        </nav>
        <Single/>
    </>
  )
}
