import React from 'react'
import Head from 'next/head'
import Single from 'components/single/single'
import Breadcrumb from '../../../components/breadcrumb/breadcrumb'

export default function Product() {
  return (
    <>
        <Head>
            <title>فروشگاه - مشاهده محصول</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <Breadcrumb 
            childrenOne='خانه'
            childrenTwo='مشاهده محصول'
        />

        <Single/>
    </>
  )
}
