import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import styles from './auth.module.scss'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faAngleLeft } from '@fortawesome/free-solid-svg-icons'



export default function Login() {
  return (
    <div className='rtl'>

      <Head>
        <title>فروشگاه - ورود</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <nav className="breadcrumb-nav">
          <div className="container">
              <ul className="breadcrumb">
                  <li><Link href="/">خانه</Link></li>
                  <FontAwesomeIcon icon={faAngleLeft} />
                  <li className='mr-1'>ورود</li>
              </ul>
          </div>
      </nav>
      <div className="page-content">
          <div className="container">
              <div className="login-popup shadows mt-3">
                  <div className="tab tab-nav-boxed tab-nav-center tab-nav-underline">
                      <ul className="nav text-uppercase">
                          <li className="nav-item">
                              <p className="nav-link active">ورود</p>
                          </li>
                      </ul>
                        <div className="tab-pane active">
                            <div className="form-group">
                                <label>نام کاربری یا آدرس ایمیل *</label>
                                <input type="text" className="form-control"/>
                            </div>
                            <div className="form-group mb-0">
                                <label>کلمه عبور *</label>
                                <input type="text" className="form-control"/>
                            </div>
                            <div className="form-checkbox d-flex align-items-center justify-content-between">
                                <input type="checkbox" className="custom-checkbox"/>
                                <label for="remember1">مرا به خاطر بسپار</label>
                                <Link href="/auth/register">ثبت نام نکرده اید ؟</Link>
                            </div>
                            <button className="btn btn-primary w-100">ورود</button>
                        </div>
                  </div>
              </div>
          </div>
      </div>
    </div>
  )
}

