import React from 'react'
import Head from 'next/head'
import Footer from '../../components/footer/footer'
import Header from '../../components/header/header'
import Link from 'next/link'
import Image from 'next/image'

export default function Compare() {
  return (
    <>
        <Head>
            <title>مقاسیه - خانه</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <main class="main rtl">
            <nav className="breadcrumb-nav ">
                <div className="container">
                    <ul className="breadcrumb">
                        <li><Link href="/">خانه</Link></li>
                        <li>مقاسیه</li>
                    </ul>
                </div>
            </nav>

            <div class="page-content mb-10 pb-2">
                <div class="container">
                    <div class="compare-table">
                        <div class="compare-row cols-xl-5 cols-lg-4 cols-md-3 cols-2 compare-products">
                            <div class="compare-col compare-field">محصول</div>
                            <div class="compare-col compare-product">
                                <Link href="#" class="btn remove-product"><i class="w-icon-times-solid"></i></Link>
                                <div class="product text-center">
                                    <figure class="product-media">
                                        <Link href="/single/product">
                                            <Image src="/assets/images/products/elements/1.jpg" alt="Product" width="228" height="257" />
                                        </Link>
                                        <div class="product-action-vertical">
                                            <Link href="/shopping/card" class="btn-product-icon btn-cart w-icon-cart"></Link>
                                            <Link href="/wishlist" class="btn-product-icon btn-wishlist w-icon-heart"></Link>
                                        </div>
                                    </figure>
                                    <div class="product-details">
                                        <h3 class="product-name"><Link href="/shopping/card">ساعت مچی مشکی الکترونیکی</Link></h3>
                                    </div>
                                </div>
                            </div>
                            <div class="compare-col compare-product">
                                <Link href="#" class="btn remove-product"><i class="w-icon-times-solid"></i></Link>
                                <div class="product text-center">
                                    <figure class="product-media">
                                        <Link href="/single/product">
                                            <Image src="/assets/images/products/elements/2.jpg" alt="Product" width="228" height="257" />
                                        </Link>
                                        <div class="product-action-vertical">
                                            <Link href="/shopping/card" class="btn-product-icon btn-cart w-icon-cart"></Link>
                                            <Link href="/wishlist" class="btn-product-icon btn-wishlist w-icon-heart"></Link>
                                        </div>
                                    </figure>
                                    <div class="product-details">
                                        <h3 class="product-name"><Link href="/shopping/card">کفش ورزشی تابستانی</Link>
                                        </h3>
                                    </div>
                                </div>
                            </div>
                            <div class="compare-col compare-product">
                                <Link href="#" class="btn remove-product"><i class="w-icon-times-solid"></i></Link>
                                <div class="product text-center">
                                    <figure class="product-media">
                                        <Link href="/single/product">
                                            <Image src="/assets/images/products/elements/3.jpg" alt="Product" width="228" height="257" />
                                        </Link>
                                        <div class="product-action-vertical">
                                            <Link href="/shopping/card" class="btn-product-icon btn-cart w-icon-cart"></Link>
                                            <Link href="/wishlist" class="btn-product-icon btn-wishlist w-icon-heart"></Link>
                                        </div>
                                    </figure>
                                    <div class="product-details">
                                        <h3 class="product-name"><Link href="/shopping/card">کفش ورزشی تابستانی</Link>
                                        </h3>
                                    </div>
                                </div>
                            </div>
                            <div class="compare-col compare-product">
                                <Link href="#" class="btn remove-product"><i class="w-icon-times-solid"></i></Link>
                                <div class="product text-center">
                                    <figure class="product-media">
                                    <Link href="/single/product">
                                            <Image src="/assets/images/products/elements/4-1.jpg" alt="Product" width="228" height="257" />
                                        </Link>
                                        <div class="product-action-vertical">
                                            <Link href="/shopping/card" class="btn-product-icon btn-cart w-icon-cart"></Link>
                                            <Link href="/wishlist" class="btn-product-icon btn-wishlist w-icon-heart"></Link>
                                        </div>
                                    </figure>
                                    <div class="product-details">
                                        <h3 class="product-name"><Link href="/shopping/card">کفش ورزشی تابستانی</Link>
                                        </h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="compare-row cols-xl-5 cols-lg-4 cols-md-3 cols-2 compare-price">
                            <div class="compare-col compare-field">قیمت</div>
                            <div class="compare-col compare-value">
                                <div class="product-price">
                                    <span class="new-price">120.000 تومان</span>
                                </div>
                            </div>
                            <div class="compare-col compare-value">
                                <div class="product-price">
                                    <span class="new-price">120.000 تومان</span>
                                    <span class="old-price">100.000</span>
                                </div>
                            </div>
                            <div class="compare-col compare-value">
                                <div class="product-price">
                                    <span class="new-price">140.000 تومان</span>
                                </div>
                            </div>
                            <div class="compare-col compare-value">
                                <div class="product-price">
                                    <span class="new-price">120.000 تومان</span>
                                </div>
                            </div>
                        </div>
                        <div class="compare-row cols-xl-5 cols-lg-4 cols-md-3 cols-2 compare-availability">
                            <div class="compare-col compare-field">دسترسی</div>
                            <div class="compare-col compare-value">نو</div>
                            <div class="compare-col compare-value">دست دوم</div>
                            <div class="compare-col compare-value">دست دوم</div>
                            <div class="compare-col compare-value">نو</div>
                        </div>
                        <div class="compare-row cols-xl-5 cols-lg-4 cols-md-3 cols-2 compare-description">
                            <div class="compare-col compare-field">توضیحات</div>
                            <div class="compare-col compare-value">
                                <ul class="list-style-none list-type-check">
                                    <li>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</li>
                                    <li>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</li>
                                    <li>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</li>
                                </ul>
                            </div>
                            <div class="compare-col compare-value">
                                <ul class="list-style-none list-type-check">
                                    <li>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</li>
                                    <li>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</li>
                                    <li>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</li>
                                </ul>
                            </div>
                            <div class="compare-col compare-value">
                                <ul class="list-style-none list-type-check">
                                    <li>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</li>
                                    <li>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</li>
                                    <li>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</li>
                                </ul>
                            </div>
                            <div class="compare-col compare-value">
                                <ul class="list-style-none list-type-check">
                                    <li>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</li>
                                    <li>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</li>
                                    <li>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</li>
                                </ul>
                            </div>
                        </div>
                        <div class="compare-row cols-xl-5 cols-lg-4 cols-md-3 cols-2 compare-reviews">
                            <div class="compare-col compare-field">امتیاز</div>
                            <div class="compare-col compare-rating">
                                <div class="ratings-container">
                                    <div class="ratings-full">
                                        <span class="ratings" style={{ width:'80%' }}></span>
                                        <span class="tooltiptext tooltip-top"></span>
                                    </div>
                                    <a href="#" class="rating-reviews">(3 Reviews)</a>
                                </div>
                            </div>
                            <div class="compare-col compare-rating">
                                <div class="ratings-container">
                                    <div class="ratings-full">
                                        <span class="ratings" style={{ width:'100%' }}></span>
                                        <span class="tooltiptext tooltip-top"></span>
                                    </div>
                                    <a href="#" class="rating-reviews">(5 Reviews)</a>
                                </div>
                            </div>
                            <div class="compare-col compare-rating">
                                <div class="ratings-container">
                                    <div class="ratings-full">
                                        <span class="ratings" style={{ width:'60%' }}></span>
                                        <span class="tooltiptext tooltip-top"></span>
                                    </div>
                                    <a href="#" class="rating-reviews">(8 Reviews)</a>
                                </div>
                            </div>
                            <div class="compare-col compare-rating">
                                <div class="ratings-container">
                                    <div class="ratings-full">
                                        <span class="ratings" style={{ width:'80%' }}></span>
                                        <span class="tooltiptext tooltip-top"></span>
                                    </div>
                                    <a href="#" class="rating-reviews">(3 Reviews)</a>
                                </div>
                            </div>
                        </div>
                        <div class="compare-row cols-xl-5 cols-lg-4 cols-md-3 cols-2 compare-category">
                            <div class="compare-col compare-field">دسته بندی</div>
                            <div class="compare-col compare-value">ساعت</div>
                            <div class="compare-col compare-value">کفش</div>
                            <div class="compare-col compare-value">ساعت</div>
                            <div class="compare-col compare-value">الکتریکی</div>
                        </div>
                        <div class="compare-row cols-xl-5 cols-lg-4 cols-md-3 cols-2 compare-meta">
                            <div class="compare-col compare-field">شماره سریال</div>
                            <div class="compare-col compare-value">MS46891344</div>
                            <div class="compare-col compare-value">MS46891389</div>
                            <div class="compare-col compare-value">MS46891349</div>
                            <div class="compare-col compare-value">MS4689158</div>
                        </div>
                        <div class="compare-row cols-xl-5 cols-lg-4 cols-md-3 cols-2 compare-color">
                            <div class="compare-col compare-field">زنگ</div>
                            <div class="compare-col compare-value">
                                <span class="swatch" style={{ backgroundColor:'#ff0000' }} title="Red"></span>
                                <span class="swatch" style={{ backgroundColor:'#00ff00' }}  title="Red"></span>
                                <span class="swatch" style={{ backgroundColor:'#0000ff' }} title="Red"></span>
                                <span class="swatch" style={{ backgroundColor:'#ECEC23' }} title="Red"></span>
                            </div>
                            <div class="compare-col compare-value">
                                <span class="swatch" style={{ backgroundColor:'#000000' }} title="Red"></span>
                                <span class="swatch" style={{ backgroundColor:'#C0C0C0' }} title="Red"></span>
                                <span class="swatch" style={{ backgroundColor:'#808080' }} title="Red"></span>
                                <span class="swatch" style={{ backgroundColor:'#0080C0' }} title="Red"></span>
                            </div>
                            <div class="compare-col compare-value">
                                <span class="swatch" style={{ backgroundColor:'#000000' }} title="Red"></span>
                                <span class="swatch" style={{ backgroundColor:'#95E8E8' }} title="Red"></span>
                                <span class="swatch" style={{ backgroundColor:'#FA0AF3' }} title="Red"></span>
                                <span class="swatch" style={{ backgroundColor:'#0A4BFA' }} title="Red"></span>
                            </div>
                            <div class="compare-col compare-value">
                                <span class="swatch" style={{ backgroundColor:'#000000' }} title="Red"></span>
                                <span class="swatch" style={{ backgroundColor:'#0000A0' }} title="Red"></span>
                                <span class="swatch" style={{ backgroundColor:'#42FDF9' }} title="Red"></span>
                                <span class="swatch" style={{ backgroundColor:'#9BA3A4' }} title="Red"></span>
                            </div>
                        </div>
                        <div class="compare-row cols-xl-5 cols-lg-4 cols-md-3 cols-2 compare-size">
                            <div class="compare-col compare-field">سایز</div>
                            <div class="compare-col compare-value">Medium, Small</div>
                            <div class="compare-col compare-value">Large, Medium</div>
                            <div class="compare-col compare-value">Small</div>
                            <div class="compare-col compare-value">Medium</div>
                        </div>
                        <div class="compare-row cols-xl-5 cols-lg-4 cols-md-3 cols-2 compare-brand">
                            <div class="compare-col compare-field">برند</div>
                            <div class="compare-col compare-value">Apple</div>
                            <div class="compare-col compare-value">New Balance</div>
                            <div class="compare-col compare-value">Node Js</div>
                            <div class="compare-col compare-value">Green Grass</div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </>
  )
}
