import Head from 'next/head'
import React from 'react'

export default function ContactUs() {
  return (
    <>
        <Head>
            <title>تماس با ما - خانه</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
    </>
  )
}
