import Head from 'next/head'
import DoubleBanner from 'components/home/banner/double-banner'
import SingleBanner from 'components/home/banner/single-banner'
import BoxWrapper from 'components/home/box-wrapper/box-wrapper'
import DiscountProduct from 'components/home/discount-product/product'
import Feature from 'components/home/feature/feature'
import AllProduct from 'components/home/product/product'
import Slider from 'components/home/slider/slider'
import TopProduct from 'components/home/top-product/product'
import Vendors from 'components/home/vendors/vendors'

export default function Home() {
  return (
    <>
      <Head>
        <title>فروشگاه - خانه</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="main">
        <Slider/>
        <Feature/>
        <BoxWrapper/>
        <Vendors/>
        <DiscountProduct/>
        <SingleBanner/>
        <AllProduct/>
        <DoubleBanner/>
        <AllProduct/>
        <TopProduct/>
      </main>
    </>
  )
}
