import React from 'react'
import Head from 'next/head'
import Link from 'next/link'


export default function Order() {
  return (
    <>
        <Head>
            <title>تکمیل خرید - خانه</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <main className="main order rtl">
            <nav className="breadcrumb-nav">
                <div className="container">
                    <ul className="breadcrumb shop-breadcrumb bb-no">
                        <li><Link href="/card">سبد خرید</Link></li>
                        <li><Link href="/checkout">فاکتور</Link></li>
                        <li className='active'><Link href="/order">تکمیل خرید</Link></li>
                    </ul>
                </div>
            </nav>

            <div className="page-content mb-10 pb-2">
                <div className="container">
                    <div className="order-success text-center font-weight-bolder text-dark">
                        <i className="fas fa-check"></i>
                        متشکرم. سفارش شما دریافت شد.
                    </div>

                    <ul className="order-view list-style-none">
                        <li>
                            <label>شماره سفارش</label>
                            <strong>945</strong>
                        </li>
                        <li>
                            <label>وضعیت</label>
                            <strong>در انتظار</strong>
                        </li>
                        <li>
                            <label>تاریخ</label>
                            <strong>1401/2/4</strong>
                        </li>
                        <li>
                            <label>جمع</label>
                            <strong>1.000.000.120 تومان</strong>
                        </li>
                        <li>
                            <label>روش پرداخت</label>
                            <strong>انتقال مستقیم بانکی</strong>
                        </li>
                    </ul>

                    <div className="order-details-wrapper mb-5">
                        <h4 className="title text-uppercase ls-25 mb-5">جزئیات سفارش</h4>
                        <table className="order-table">
                            <thead>
                                <tr>
                                    <th className="text-dark">محصول</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <a>ژاکت چاپ نخل</a>&nbsp;<strong>x 1</strong><br/>
                                        فروشنده : <a>فروشنده 1</a>
                                    </td>
                                    <td>120.000 تومان</td>
                                </tr>
                                <tr>
                                    <td>
                                        <a>کوله پشتی قهوه ای</a>&nbsp;<strong>x 1</strong><br/>
                                        فروشنده : <a>فروشنده 1</a>
                                    </td>
                                    <td>150.000 تومان</td>
                                </tr>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>جمع فرعی:</th>
                                    <td>120.000 تومان</td>
                                </tr>
                                <tr>
                                    <th>حمل:</th>
                                    <td>نرخ ثابت</td>
                                </tr>
                                <tr>
                                    <th>روش پرداخت:</th>
                                    <td>انتقال مستقیم بانکی</td>
                                </tr>
                                <tr className="total">
                                    <th className="border-no">جمع:</th>
                                    <td className="border-no">160.000 تومان</td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>

                    <div className="sub-orders mb-10">
                        <h4 className="title mb-5 font-weight-bold ls-25">سفارشات فرعی</h4>
                        <div className="alert alert-icon alert-inline mb-5" style={{ padding:'20px' }}>
                            <i className="w-icon-exclamation-triangle"></i>
                            <strong>توجه داشته باشید: </strong>این سفارش دارای محصولاتی از چندین فروشنده است. بنابراین ما این سفارش را به چندین سفارش فروشنده تقسیم کردیم. هر سفارش توسط فروشنده مربوطه به طور مستقل انجام می شود.
                        </div>
                        <table className="order-subtable">
                            <thead>
                                <tr>
                                    <th className="order">سفارش</th>
                                    <th className="date">تاریخ</th>
                                    <th className="status">وضعیت</th>
                                    <th className="total">جمع</th>
                                    <th className="action"></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td className="order">950</td>
                                    <td className="date">1400/1/2/</td>
                                    <td className="status">در انتظار</td>
                                    <td className="total">40.00 برای 1 مورد</td>
                                </tr>
                                <tr>
                                    <td className="order">120</td>
                                    <td className="date">1400/1/2/</td>
                                    <td className="status">در انتظار</td>
                                    <td className="total">40.00 برای 1 مورد</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <div id="account-addresses">
                        <div className="row">
                            <div className="col-sm-6 mb-8">
                                <div className="ecommerce-address billing-address">
                                    <h4 className="title title-underline ls-25 font-weight-bold">آدرس</h4>
                                    <address className="mb-4">
                                        <table className="address-table">
                                            <tbody>
                                                <tr>
                                                    <td>جان دو</td>
                                                </tr>
                                                <tr>
                                                    <td>کونیا</td>
                                                </tr>
                                                <tr>
                                                    <td>وال استریت</td>
                                                </tr>
                                                <tr>
                                                    <td>کالیفرنیا</td>
                                                </tr>
                                                <tr>
                                                    <td>ایران</td>
                                                </tr>
                                                <tr>
                                                    <td>92020</td>
                                                </tr>
                                                <tr>
                                                    <td>1112223334</td>
                                                </tr>
                                                <tr className="email">
                                                    <td>nicework125@gmail.com</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </address>
                                </div>
                            </div>
                            <div className="col-sm-6 mb-8">
                                <div className="ecommerce-address shipping-address">
                                    <h4 className="title title-underline ls-25 font-weight-bold">آدرس حمل و نقل</h4>
                                    <address className="mb-4">
                                        <table className="address-table">
                                            <tbody>
                                                <tr>
                                                    <td>جان دو</td>
                                                </tr>
                                                <tr>
                                                    <td>کونیا</td>
                                                </tr>
                                                <tr>
                                                    <td>وال استریت</td>
                                                </tr>
                                                <tr>
                                                    <td>کالیفرنیا</td>
                                                </tr>
                                                <tr>
                                                    <td>ایران</td>
                                                </tr>
                                                <tr>
                                                    <td>92020</td>
                                                </tr>
                                                <tr>
                                                    <td>1112223334</td>
                                                </tr>
                                                <tr className="email">
                                                    <td>nicework125@gmail.com</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </address>
                                </div>
                            </div>
                        </div>
                    </div>

                    <Link href="/checkout" className="btn btn-dark btn-rounded btn-icon-left btn-back mt-6"><i className="w-icon-long-arrow-left"></i> بازگشت به فهرست</Link>
                </div>
            </div>
        </main>

    </>
  )
}
