import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Fillter from '../../components/shop/fillter'
import Banner from '../../components/shop/banner'
import Toolbox from '../../components/shop/toolbox'
import Pagination from '../../components/shop/pagination'
import Product from '../../components/shop/product'
import Breadcrumb from '../../components/breadcrumb/breadcrumb'

export default function Shop() {
  return (
    <>
        <Head>
            <title>فروشگاه - خانه</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <Breadcrumb 
            childrenOne='خانه'
            childrenTwo='فروشگاه' 
        />

        <main className="main rtl">
            <div className="page-content mb-10">
                <div className="container">
                    <div className="shop-content row gutter-lg">
                        <Fillter/>

                        <div className="main-content">
                            <Banner/>

                            <Toolbox/>

                            <Product/>
                            
                            <Pagination/>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    
    </>
  )
}
