import React, { useState } from 'react'
import Link from 'next/link'
import Head from 'next/head'

export default function Faq() {

    // faq data
    const data = [
        {id:1 , title:'چه روش های حمل و نقل موجود است؟' , description:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.'},
        {id:2 , title:'چه شیوه های پرداختی مورد قبول است؟' , description:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.'},
        {id:3 , title:'چه روش های حمل و نقل موجود است؟' , description:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.'},
        {id:4 , title:'چه شیوه های پرداختی مورد قبول است؟' , description:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.'},
    ]
    const [faqs , setFaqs] = useState(data)

  return (
    <>
        <Head>
            <title>حریم خصوصی - خانه</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <nav className="breadcrumb-nav rtl">
            <div className="container">
                <ul className="breadcrumb">
                    <li><Link href="/">خانه</Link></li>
                    <li>حریم خصوصی</li>
                </ul>
            </div>
        </nav>


        <main className="main mt-5 rtl">
            <div className="page-content faq">
                <div className="container">
                    <section className="content-title-section">
                        <h3 className="title title-simple justify-content-center bb-no pb-0">سوالات متداول</h3>
                        <p className="description text-center">می‌توانید با <b>نیباک</b> به راحتی سوالات را نشان دهید.</p>
                    </section>

                    <section className="mb-6">
                        <h4 className="title title-center mb-5">اطلاعات حمل و نقل</h4>
                        <div className="row">
                            {faqs.map((i , index)=> {
                                return(
                                    <div key={index} className="card accordion accordion-bg accordion-gutter-md accordion-border col-md-6 mb-5">
                                        <div className="card-header">
                                            <a href="#collapse1-1" className="collapse">{i.title}</a>
                                        </div>
                                        <div id="collapse1-1" className="card-body expanded">
                                            <p className="mb-0">
                                                {i.description}
                                            </p>
                                        </div>
                                    </div>
                                )
                            })}
                        </div>
                        
                    </section>

                    <section className="mb-10">
                        <h4 className="title title-center mb-5">پرداخت</h4>
                        <div className="row">
                            {faqs.map((i , index)=> {
                                return(
                                    <div key={index} className="card accordion accordion-bg accordion-gutter-md accordion-border col-md-6 mb-5">
                                        <div className="card-header">
                                            <a href="#collapse1-1" className="collapse">{i.title}</a>
                                        </div>
                                        <div id="collapse1-1" className="card-body expanded">
                                            <p className="mb-0">
                                                {i.description}
                                            </p>
                                        </div>
                                    </div>
                                )
                            })}
                        </div>
                        
                    </section>
                </div>
            </div>
        </main>
    </>
  )
}
