import React, { useState } from 'react'
import Link from 'next/link'
import Head from 'next/head'
import Header from '../../../components/header/header'
import Footer from '../../../components/footer/footer'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faAngleLeft } from '@fortawesome/free-solid-svg-icons'

export default function Faq() {

    // faq data
    const data = [
        {id:1 , title:'چه روش های حمل و نقل موجود است؟' , description:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.'},
        {id:2 , title:'چه شیوه های پرداختی مورد قبول است؟' , description:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.'},
        {id:3 , title:'چه روش های حمل و نقل موجود است؟' , description:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.'},
        {id:4 , title:'چه شیوه های پرداختی مورد قبول است؟' , description:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.'},
    ]
    const [faqs , setFaqs] = useState(data)

  return (
    <>
        <Head>
            <title>حریم خصوصی - خانه</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <Header/>

        <nav className="breadcrumb-nav rtl">
            <div className="container">
                <ul className="breadcrumb">
                    <li><Link href="/">خانه</Link></li>
                    <FontAwesomeIcon icon={faAngleLeft} />
                    <li className='mr-1'>حریم خصوصی</li>
                </ul>
            </div>
        </nav>

        <main class="main mt-5 rtl">
            <div class="page-content faq">
                <div class="container">
                    <section class="content-title-section">
                        <h3 class="title title-simple justify-content-center bb-no pb-0">سوالات متداول</h3>
                        <p class="description text-center">می‌توانید با <b>نیباک</b> به راحتی سوالات را نشان دهید.</p>
                    </section>

                    <section class="mb-6">
                        <h4 class="title title-center mb-5">اطلاعات حمل و نقل</h4>
                        <div class="row">
                            {faqs.map((i , index)=> {
                                return(
                                    <div key={index} class="card accordion accordion-bg accordion-gutter-md accordion-border col-md-6 mb-5">
                                        <div class="card-header">
                                            <a href="#collapse1-1" class="collapse">{i.title}</a>
                                        </div>
                                        <div id="collapse1-1" class="card-body expanded">
                                            <p class="mb-0">
                                                {i.description}
                                            </p>
                                        </div>
                                    </div>
                                )
                            })}
                        </div>
                        
                    </section>

                    <section class="mb-10">
                        <h4 class="title title-center mb-5">پرداخت</h4>
                        <div class="row">
                            {faqs.map((i , index)=> {
                                return(
                                    <div key={index} class="card accordion accordion-bg accordion-gutter-md accordion-border col-md-6 mb-5">
                                        <div class="card-header">
                                            <a href="#collapse1-1" class="collapse">{i.title}</a>
                                        </div>
                                        <div id="collapse1-1" class="card-body expanded">
                                            <p class="mb-0">
                                                {i.description}
                                            </p>
                                        </div>
                                    </div>
                                )
                            })}
                        </div>
                        
                    </section>
                </div>
            </div>
        </main>

        <Footer/>
    </>
  )
}
