import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Cards from '../../../components/card/cards'
import Totals from '../../../components/card/totals'



export default function Card() {
  return (
    <>
      <Head>
          <title>سبد خرید - خانه</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className="main cart rtl">

            <nav className="breadcrumb-nav">
                <div className="container">
                    <ul className="breadcrumb shop-breadcrumb bb-no">
                        <li className="active"><Link href="/shopping/card">سبد خرید</Link></li>
                        <li><Link href="/shopping/checkout">فاکتور</Link></li>
                        <li><Link href="/shopping/order">تکمیل خرید</Link></li>
                    </ul>
                </div>
            </nav>

            <div className="page-content">
                <div className="container">
                    <div className="row gutter-lg mb-10">
                        <Cards/>
                        <Totals/>
                    </div>
                </div>
            </div>
        </main>

    </>
  )
}
